const TYPE = {
  CREATE_NEW_TASK: "CREATE_NEW_TASK",
  UPDATE_TASK: "UPDATE_TASK",
  DELETE_TASK: "DELETE_TASK",

  //
  GET_ALL_TASK: "GET_ALL_TASK",
  GET_TASK_BY_ID: "GET_TASK_BY_ID",

  //
  SEARCH_TASK: "SEARCH_TASK",
};

export default TYPE;
